### ISSUE TITLE
Incorrect FSLogix guidance provided

### ISSUE THREAD

**Issue by JamesKindon** [govau/desktop.gov.au#153]
There are a number of incorrect configurations specified in the reference architectures, particularly focused on VHD access types, Windows Search configurations, outage impacts, redirections XML, Teams and SharePoint configurations, Cloud Cache (not referenced as part of the architecture but settings enabled which are only associated with Cloud Cache) - need to review this guidance for accuracy

**Comment by oobedan** [comment]
Thanks for the feedback, will revisit the settings. Cloudcache def not used in architecture due to performance issues seen.

Redirections is a sticking point, would prefer to reference a crowd sourced location or just keep it thin. There doesn't seem to be a single source out there that keeps an up to date.

**Comment by aaronparker** [comment]
For the `redirections.xml`, the best approach would be to keep it simple. I've pared down the exclusions to the minimum including Microsoft recommended exclusions in a list maintain here: [https://github.com/aaronparker/fslogix/blob/main/Redirections/Redirections.csv](https://github.com/aaronparker/fslogix/blob/main/Redirections/Redirections.csv). Most environments shouldn't need any more than this.

**Comment by JamesKindon** [comment]
Happy to provide some input if it would be of assistance - one of the focal points for me would be around your outage scenarios and guidance around the cache components, everything cache is based on cloud-cache with FSLogix, else it is a direct mount to the VHD's with all the fun that goes with it - reach out if you need clarity or have questions

**Comment by oobedan** [comment]
Thanks will update, yeah the intention was not to use cloud-cache due to the logon performance seen (however does offer better resilience), in favour of direct mounted via Azure files/or NetApp Files (which are very highly available in their own right). We should probably add some clarity around the rationale there and outline risk there.

**Comment by JamesKindon** [comment]
you shouldn't be seeing delays on cloud cache any more - there should be next to no tax unless there are bottlenecks (not saying you should use it, just that the problems were resolved a while back)

I have plenty of stuff here that might help you https://jkindon.com/, specifically on FSLogix https://jkindon.com/tags/#FSLogix

**Comment by oobedan** [comment]
@JamesKindon these corrections to FSlogix configuration should now be merged in live.

**Comment by oobedan** [comment]
Closing issue as corrections have been made through #172. Feel free to reopen or create a new ticket otherwise.
